---
all:
  hosts:
    k8sMaster:
      ansible_host: "52.140.209.163"
      ansible_port: 22     
      ansible_connection: ssh        
      ansible_ssh_user: k8s
  children:
    k8sNodes:
      host: