---
all:
  children:
    MasterNode:
      hosts:
        k8sMaster:
          ansible_host: 192.168.1.110
          ansible_port: 22     
          ansible_connection: ssh        
          ansible_ssh_user: lianism
    k8sWorker:
      hosts:
        worker0:
          ansible_host: 192.168.1.111
          ansible_port: 22     
          ansible_connection: ssh        
          ansible_ssh_user: lianism
