---
all:
  hosts:
    k8sMaster:
      ansible_host: "{{ k8sMaster_pub_ip }}"
      ansible_port: 22     
      ansible_connection: ssh        
      ansible_ssh_user: k8s
    k8sWorker:
      ansible_host: "{{ k8sWorker_pub_ip }}"
      ansible_port: 22     
      ansible_connection: ssh        
      ansible_ssh_user: k8s