---
- name: "ping"
  hosts: k8sMaster
  tasks:
    # task 1
    - name: test connection
      ping:
      register: message

    # task 2
    - name: print debug message
      debug:
        msg: "{{ message }}"

- name: "install role"
  hosts: k8sMaster
  roles:
    - { role: crio, become: True }