#source: https://github.com/cri-o/packaging/blob/main/README.md
- name: Install the dependencies for adding repositories
  ansible.builtin.shell:
    cmd: |
      apt-get update 
      apt-get install -y software-properties-common curl
  args:
    executable: /bin/bash
  become: yes

- name: remove the old kerying
  ansible.builtin.shell:
    cmd: |
      mkdir -p /etc/apt/keyrings
      [ -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg ] && rm /etc/apt/keyrings/kubernetes-apt-keyring.gpg || true
      [ -f cri-o-apt-keyring.gpg ] && rm cri-o-apt-keyring.gpg || true
  args:
    executable: /bin/bash
  become: yes

- name: Add the Kubernetes repository
  ansible.builtin.shell:
    cmd: |
      curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ KUBERNETES_VERSION }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ KUBERNETES_VERSION }}/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
  args:
    executable: /bin/bash
  become: yes

- name: Add the CRI-O repository
  ansible.builtin.shell:
    cmd: |
      curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ CRIO_VERSION }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
      echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ CRIO_VERSION }}/deb/ /" | tee /etc/apt/sources.list.d/cri-o.list
  args:
    executable: /bin/bash
  become: yes


- name: Install the packages
  ansible.builtin.shell:
    cmd: |
      apt-get update
      apt-get install -y cri-o kubelet kubeadm kubectl
  args:
    executable: /bin/bash
  become: yes


- name: Start CRI-O
  ansible.builtin.shell:
    cmd: |
      systemctl start crio.service
  args:
    executable: /bin/bash
  become: yes

- name: Bootstrap a cluster
  ansible.builtin.shell:
    cmd: |
      swapoff -a
      modprobe br_netfilter
      sysctl -w net.ipv4.ip_forward=1
  args:
    executable: /bin/bash
  become: yes

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
