---
# the container-run time var is pass through start.sh
- include_role:
    name: "{{ runtime }}"

- name: Update OS to latest
  package:
    name: '*'
    state: latest

- name: Enable kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kernelModules }}"

- name: add the sysctl setting
  sysctl:
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    state: present
    sysctl_file: 99-kubernetes-cri.conf
    reload: yes
  loop: "{{ sysctl }}"

- name: install required apt
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop: "{{ required_apt }}"

- name: Add the apt key
  shell: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add specified k8s repository
  ansible.builtin.apt_repository:
    repo: "{{ item.source }}"
    state: present
    filename: "{{ item.file_name }}"
  loop: "{{ apt_urls }}"

- name: install k8s
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Hold kubeadm
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl